export const AUTH_VALIDATE_REDUX_CONSTANTS = {
  CHANGE_AUTH_ERROR_STATUS: "CHANGE_ERROR_STATUS",
  CHANGE_INPUT_VALUE: "CHANGE_INPUT_VALUE",
  SHOW_PASSWORD: "SHOW_PASSWORD",
  SHOW_CONFIRM_PASSWORD: "SHOW_CONFIRM_PASSWORD",
  IS_PASSWORD_MATCH: "IS_PASSWORD_MATCH",
  RESET_STATES: "RESET_STATES",
};
